### ISSUE TITLE
ETQ utilisateur : Je peux faire un export des données saisies sous format Excel

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson#18]
# Contexte
Le groupe d'élève a finalisé au moins un des secteurs d'émission de son établissement et les professeurs et élèves peuvent maintenant faire un export sous format Excel de bilan par secteurs de l'empreinte carbone de leur établissement

# Tests d’acceptance
- [ ] Le bouton télécharge le document est facilement trouvable sur la page d'accueil

# Cas limites
- [ ] Faire des tests en cas de valeurs incohérente pour voir si cela peut casser le CSV

# Infos Tech
Utiliser une bibliothèque d'export de CSV commune en JS
Pas besoin de stocker le résultat des calculs dans la BDD

**Comment by khalilelhazmiri** [comment]
en attendant la finalisation de la tache [https://github.com/ABC-TransitionBasCarbone/clickson/issues/6](ETQ utilisateur : je peux saisir les données énergies de l'établissement #6 ) car j'ai pas de données effectuer l'export

**Comment by RomainCrevecoeur** [comment]
![image](https://github.com/user-attachments/assets/66219759-5b80-4752-8c12-a6b79718ab96)
@Teddy est ce que tu peux me dire si c'est ok pour toi d'avoir ce format de restitution Excel ?

**Comment by RomainCrevecoeur** [comment]
[CLICKS ON_Calculator.xlsx](https://github.com/user-attachments/files/16660157/CLICKS.ON_Calculator.xlsx)
