### ISSUE TITLE
ETQ visiteur (FO) : Je peux m'enregistrer sur le site (formulaire)

### ISSUE THREAD

**Issue by khalilelhazmiri** [ABC-TransitionBasCarbone/clickson#28]
# Contexte
Le visiteur était sur la page d'authentification mais n'avais pas de compte alors il a cliqué sur "se créer un compte"

# Tests d’acceptance
- [ ] Le visiteur professeur peut créer un compte pour son établissement
- [ ] Nom de l'établissement, Nombre élèves, Nombre personnels, Année de construction, Adresse

# Cas limites
- [x] L'utilisateur donne une adresse email non valide -> erreur
- [x] L'utilisateur utilise une adresse email déjà enregistré sur wordpress --> erreur

# Infos Tech
Utiliser l'api graphql pour créer un nouvel utilisateur

![Image](https://github.com/user-attachments/assets/dea49339-4db8-4291-90ef-f01a54be6f23)

**Comment by khalilelhazmiri** [comment]
Discuté avec @RomainCrevecoeur , on va utiliser une liste déroulante des pays !

**Comment by RomainCrevecoeur** [comment]
https://clickson-git-develop-abc-transitionbascarbones-projects.vercel.app/signup

**Comment by teddyABC24** [comment]
- Il faudrait rajouter "ville" sous le champ "école" pour éviter de potentiels doublons dans les exports et BDD
- Remplacer "école" par "Nom de mon établissement"
- Le message d'erreur comporte quelques fautes, remplacer par "Un compte est déjà associé à cette adresse email, cliquez ici pour vous connecter (lien) ou choisissez une autre adresse email." 
![Image](https://github.com/user-attachments/assets/9c455833-7abd-4589-802e-5a7c7c7dc76f)
- Toutes les langues sont affichées en français pour l'instant
