### ISSUE TITLE
ETQ utilisateur : Je vois un graphique sur la page du Dashboard

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson#3]
# Contexte
Affichage graphique de la part de chaque secteurs d'activité dans l'empreinte carbone pour l'établissement de l'utilisateur

# Tests d’acceptance

- [x] Avoir accès à la page de Dashboard. 
- [x] Voir un graphique avec des proportions des différents secteurs
- [x] Afficher le total des émission de CO2
- [x] Il est possible d'afficher ou de masquer un secteur

# Cas limites
Que faire quand on désélectionne tous les secteurs ?

# Infos Tech
Utiliser [mui react-charts?](https://mui.com/x/react-charts/pie/)
Avec les % https://mui.com/x/react-charts/pie-demo/#piechartwithcustomizedlabel
Pour le détail des https://mui.com/x/react-charts/bars/
Utiliser des données en dur pour le moment
Utiliser MUI

![Image](https://github.com/user-attachments/assets/ca938995-a918-401a-899a-9b5377fc5d5c)

**Comment by RomainCrevecoeur** [comment]
Idée pour un autre ticket

- [ ]  Passer de Doughnut en Pie
- [ ]  Mettre les pourcentages

**Comment by RomainCrevecoeur** [comment]
https://clickson-git-develop-abc-transitionbascarbones-projects.vercel.app/dashboard

**Comment by teddyABC24** [comment]
Sur l'entête, peut-on rajouter automatiquement le nom de l'établissement, voire sa ville ? 

![Image](https://github.com/user-attachments/assets/836c860d-13ca-4d0c-8336-eda30fecebad)

- Sur le diagramme, lorsque la donnée est très faible (ex : déplacements), on ne la voit pas. Pour y remédier, peut-être plutôt afficher les postes d'émission autour du diagramme avec des traits qui pointent vers la bonne couleur ?
- Afficher également les pourcentages pour chaque poste d'émission sur le diagramme
- Comme dit par Romain plus haut, proposer d'autres types de graphiques, en l'occurrence un histogramme
