### ISSUE TITLE
Retour Recette Dashboard

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson#38]
> Sur l'entête, peut-on rajouter automatiquement le nom de l'établissement, voire sa ville ? 
> 
> ![Image](https://github.com/user-attachments/assets/836c860d-13ca-4d0c-8336-eda30fecebad)
> 
> - [ ] - Sur le diagramme, lorsque la donnée est très faible (ex : déplacements), on ne la voit pas. Pour y remédier, peut-être plutôt afficher les postes d'émission autour du diagramme avec des traits qui pointent vers la bonne couleur ?
> - [ ] - Afficher également les pourcentages pour chaque poste d'émission sur le diagramme
> - [ ] - Comme dit par Romain plus haut, proposer d'autres types de graphiques, en l'occurrence un histogramme
> - [ ] Passer de Doughnut en Pie
> - [ ] Mettre les pourcentages 

 _Originally posted by @teddyABC24 in [#3](https://github.com/ABC-TransitionBasCarbone/clickson/issues/3#issuecomment-2298864148)_

**Comment by teddyABC24** [comment]
Sur les libellés du graphique : rajouter des cases à cocher pour chaque catégorie (sur la gauche des libellés). La fonctionnalité permettra de faire apparaitre ou disparaitre les catégories sur le graphique
