### ISSUE TITLE
Retour recette enregistrement

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson#39]
> - [ ] Il faudrait rajouter "ville" sous le champ "école" pour éviter de potentiels doublons dans les exports et BDD
> - [ ] Remplacer "école" par "Nom de mon établissement"
> - [ ] Le message d'erreur comporte quelques fautes, remplacer par "Un compte est déjà associé à cette adresse email, cliquez ici pour vous connecter (lien) ou choisissez une autre adresse email."  ![Image](https://github.com/user-attachments/assets/9c455833-7abd-4589-802e-5a7c7c7dc76f)
> - [ ] Toutes les langues sont affichées en français pour l'instant 

 _Originally posted by @teddyABC24 in [#28](https://github.com/ABC-TransitionBasCarbone/clickson/issues/28#issuecomment-2298721212)_

**Comment by khalilelhazmiri** [comment]
- [ ] ajout de champ ville et département (code postale)
