### ISSUE TITLE
Page "s'enregistrer"

### ISSUE THREAD

**Issue by khalilelhazmiri** [ABC-TransitionBasCarbone/clickson#58]
Une fois que l'on a créé son compte : 
- peut-on rajouter champ de saisie de confirmation de mot de passe ?
- redirection vers la page de l'établissement
- l'utilisateur doit recevoir un mail automatique de confirmation de création de son compte
- sur la page d'accueil : le bouton "connexion" mouline et rien ne se passe

Problème rencontré : 
un nouveau compte a été créé avec mon adresse teddy.courtaux@abc-transitionbascarbone.fr alors que j'en possédais déjà un

**Comment by RomainCrevecoeur** [comment]
- [ ] Regarder http://abc-transitionbascarbone.scienceontheweb.net/ pour l'envoie de mail
