### ISSUE TITLE
ETQ professeur : j'ai accès à une page d'accueil pour gérer les sessions des élèves

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson#7]
# Contexte
Le visiteur s'est connecté en tant que professeur.
Il a maintenant accès à une page d'accueil avec le nom de son établissement
Un professeur doit pouvoir créer des groupes d'élève puis de les associer à une session. Pour l'instant le back n'est pas prêt mais on peut créer ici uniquement le visuel, sans fonctionnement derrière les boutons pour valider les groupes et les sessions.
Dans la partie création de session, on a besoin d'avoir des groupes d'élève, pour l'instant, on peut mettre en dur dans le code un tableau de groupes d'élève afin de pouvoir tester le visuel.

# Tests d’acceptance
- [x] Affichage du nom de l'établissement
- [x] Nombre élèves Nombre personnels Année de construction Adresse
- [x] J'ai accès à la page de création d'un groupe
- [x] J'ai accès à la page de création d'une session
- [ ] Je peux y définir les groupes qui s'occupent de chaque section de ma session
- [ ] Pour chaque session je peux définir si celle-ci doit être avancé ou non

# Cas limites
- [ ] L'utilisateur ne peut pas créer plus de 100 sessions

# Infos Tech
Requête de Wordpress pour récupérer tous les groupes d'utilisateurs de l'établissement

![Image](https://github.com/user-attachments/assets/97342e55-8525-436f-a458-a56aead7a376)

**Comment by cmolle** [comment]
@khalilelhazmiri  que penses-tu de créer un premier ticket pour faire uniquement la partie visuel de ce ticket ?

**Comment by teddyABC24** [comment]
En entête : 
peut-on rajouter la possibilité de rajouter une photo de profil ?
année de construction : je crains qu'ils ne possèdent pas toujours cette donnée, peut-on plutôt leur poser la question "mon établissement a plus de 20 ans : oui/non. -> cette réponse aura des répercussions sur le poste "immobilisations".  A rediscuter ensemble, merci !

Sous la colonne "actions", rajouter une action "entrer" 
Afficher un pop up pour confirmer la suppression d'une session
